services:
  redfish-emu:
    build: .
    ports:
      - "8008:8008"
    volumes:
      - ./data:/data
    environment:
      - DB_PATH=/data/redfish.db

    networks:
      - redfish-net

networks:
  redfish-net:
    external: true
